export { default as Navbar } from './navbar'
export { default as HeroCarousel } from './hero-carousel'
export { default as SocialSection } from './social-section'
export { default as IntroAnimation } from './intro-animation'
export { default as HomePage } from './home-page'
export { default as LoginPage } from './login-page'
export { default as RegistroPage } from './registro-page'