import type {
  AdminDashboardView,
  AdminSidebarGroup,
} from './admin-dashboard.types'

export const adminSidebarGroups: AdminSidebarGroup[] = [
  {
    id: 'grupo-general',
    title: 'General',
    items: [
      {
        id: 'nav-inicio',
        label: 'Centro de control',
        icon: 'home',
        viewId: 'inicio',
        note: 'Vista principal del panel administrativo',
      },
    ],
  },
  {
    id: 'grupo-modulos',
    title: 'Modulos',
    items: [
      {
        id: 'nav-usuarios',
        label: 'Usuarios y roles',
        icon: 'users',
        note: 'USUARIO, CLIENTE, EMPLEADO, ADMINISTRADOR',
        children: [
          {
            id: 'nav-usuarios-general',
            label: 'Usuarios en general',
            icon: 'users',
            viewId: 'usuarios-general',
            note: 'CRUD real, roles y borrado logico desde la base de datos',
          },
          {
            id: 'nav-usuarios-empleados',
            label: 'Empleados',
            icon: 'users',
            viewId: 'usuarios-empleados',
            note: 'Busqueda, paginacion y asignacion operativa real del personal',
          },
        ],
      },
      {
        id: 'nav-sucursales',
        label: 'Sucursales y contratos',
        icon: 'store',
        viewId: 'sucursales',
        note: 'SUCURSAL y CONTRATO',
      },
      {
        id: 'nav-catalogo',
        label: 'Catalogo y stock',
        icon: 'box',
        note: 'CATEGORIA_PRODUCTO, PRODUCTO y configuracion visual real',
        children: [
          {
            id: 'nav-catalogo-personalizacion',
            label: 'Personalizacion Bouquets',
            icon: 'sparkles',
            viewId: 'catalogo-personalizacion',
            note: 'Bouquets, flores, mascara y degradado conectados a la base de datos',
          },
        ],
      },
      {
        id: 'nav-campanas',
        label: 'Campanas y fidelizacion',
        icon: 'sparkles',
        viewId: 'campanas',
        note: 'PROMOCION, PRODUCTO_PROMOCION, PUNTAJE',
      },
      {
        id: 'nav-ventas',
        label: 'Ventas y pagos',
        icon: 'credit-card',
        viewId: 'ventas',
        note: 'PEDIDO, PEDIDO_PRODUCTO, PAGO, METODO_PAGO',
      },
      {
        id: 'nav-entregas',
        label: 'Entregas',
        icon: 'truck',
        viewId: 'entregas',
        note: 'ENTREGA enlazada con PEDIDO y EMPLEADO',
      },
    ],
  },
]

export const adminDefaultViewId = 'inicio'

export const adminDashboardViews: AdminDashboardView[] = [
  {
    id: 'inicio',
    icon: 'home',
    label: 'Centro de control',
    eyebrow: 'Vista principal',
    title: 'Centro de control',
    description: 'Desde aqui cambias de modulo sin bajar por secciones largas ni saltar a otras zonas del dashboard.',
    emptyState: 'Esta consola no muestra cifras inventadas. Si aun no hay datos conectados, la vista se mantiene limpia y enfocada en la estructura real.',
    accent: 'vino',
    cards: [
      {
        id: 'inicio-sesion',
        title: 'Sesion del administrador',
        description: 'El acceso actual se conserva con la sesion de Django y mantiene la ruta administrativa activa.',
        note: 'Fuente real: autenticacion y me_view.',
        tone: 'vino',
        tags: ['Sesion', 'Administrador', 'Backend Django'],
      },
      {
        id: 'inicio-navegacion',
        title: 'Vista unica por boton',
        description: 'Cada icono lateral reemplaza el contenido central en la misma pantalla, sin desplazarte hacia bloques mas abajo.',
        note: 'Comportamiento tipo panel administrativo.',
        tone: 'oro',
        tags: ['Una vista', 'Cambio inmediato', 'Sin anclas'],
      },
      {
        id: 'inicio-estructura',
        title: 'Estructura real del negocio',
        description: 'Los modulos corresponden a tus tablas y relaciones principales, no a tarjetas artificiales ni a resumenes simulados.',
        note: 'Si no existe un dato conectado, se deja en espera.',
        tone: 'hoja',
        tags: ['Esquema real', 'Sin inventar', 'Modulos reales'],
      },
    ],
  },
  {
    id: 'usuarios-general',
    icon: 'users',
    label: 'Usuarios en general',
    eyebrow: 'Identidad y acceso',
    title: 'Usuarios en general',
    description: 'Gestiona usuarios base, clientes, empleados y administradores desde el dashboard con datos reales.',
    emptyState: 'Esta vista ya no usa relleno visual; si no hay usuarios en la base de datos, la lista queda vacia.',
    accent: 'vino',
    cards: [],
  },
  {
    id: 'usuarios-empleados',
    icon: 'users',
    label: 'Empleados',
    eyebrow: 'Operacion interna',
    title: 'Empleados',
    description: 'Concentra la gestion operativa del personal y su estado real dentro del negocio.',
    emptyState: 'Si no hay empleados registrados en la base de datos, la lista se mantiene vacia.',
    accent: 'grafito',
    cards: [],
  },
  {
    id: 'sucursales',
    icon: 'store',
    label: 'Sucursales y contratos',
    eyebrow: 'Cobertura operativa',
    title: 'Sucursales y contratos',
    description: 'Organiza la estructura fisica del negocio y la relacion contractual de cada sede o responsable.',
    emptyState: 'Esta vista quedara vacia hasta que existan datos reales de sucursales, responsables y contratos activos.',
    accent: 'oro',
    cards: [
      {
        id: 'sucursales-sede',
        title: 'Sucursales',
        description: 'Preparado para nombre, ubicacion y estado operativo de cada sede.',
        note: 'Tabla relacionada: SUCURSAL.',
        tone: 'oro',
        tags: ['SUCURSAL', 'Ubicacion', 'Cobertura'],
      },
      {
        id: 'sucursales-contratos',
        title: 'Contratos',
        description: 'Panel enfocado en vigencias, condiciones y control contractual enlazado al negocio.',
        note: 'Tabla relacionada: CONTRATO.',
        tone: 'vino',
        tags: ['CONTRATO', 'Vigencia', 'Control'],
      },
      {
        id: 'sucursales-coordinacion',
        title: 'Coordinacion administrativa',
        description: 'Espacio para el cruce entre administradores, empleados y sedes cuando la data este conectada.',
        note: 'Relacion operativa entre tablas reales.',
        tone: 'hoja',
        tags: ['Administrador', 'Empleado', 'Sucursal'],
      },
    ],
  },
  {
    id: 'catalogo',
    icon: 'box',
    label: 'Catalogo y stock',
    eyebrow: 'Inventario comercial',
    title: 'Catalogo y stock',
    description: 'Concentra categorias, productos, inventario y precio unitario dentro de un mismo modulo.',
    emptyState: 'Sin conexion de inventario no se renderizan cantidades. Solo se conserva la estructura lista para tus datos reales.',
    accent: 'hoja',
    cards: [
      {
        id: 'catalogo-categorias',
        title: 'Categorias de producto',
        description: 'Segmentacion principal para clasificar flores, bouquets y demas lineas del catalogo.',
        note: 'Tabla relacionada: CATEGORIA_PRODUCTO.',
        tone: 'hoja',
        tags: ['Categoria', 'Clasificacion', 'Catalogo'],
      },
      {
        id: 'catalogo-productos',
        title: 'Productos',
        description: 'Contenedor natural para nombre, descripcion, stock, precio y estado comercial.',
        note: 'Tabla relacionada: PRODUCTO.',
        tone: 'vino',
        tags: ['PRODUCTO', 'Precio', 'Estado'],
      },
      {
        id: 'catalogo-stock',
        title: 'Control de stock',
        description: 'Reserva el espacio para entradas, salidas y disponibilidad sin forzar numeros simulados.',
        note: 'Los conteos deben venir del backend cuando existan endpoints reales.',
        tone: 'oro',
        tags: ['Stock', 'Inventario', 'Disponibilidad'],
      },
    ],
  },
  {
    id: 'catalogo-personalizacion',
    icon: 'sparkles',
    label: 'Personalizacion Bouquets',
    eyebrow: 'Catalogo conectado',
    title: 'Personalizacion Bouquets',
    description: 'Gestion real de bouquets, flores, mascaras internas y stock desde el panel del administrador.',
    emptyState: 'Esta vista se conecta al backend y deja de usar datos mock en la tienda.',
    accent: 'hoja',
    cards: [],
  },
  {
    id: 'campanas',
    icon: 'sparkles',
    label: 'Campanas y fidelizacion',
    eyebrow: 'Promocion y relacion con clientes',
    title: 'Campanas y fidelizacion',
    description: 'Este modulo concentra promociones, cruces con productos y puntaje asociado a la experiencia del cliente.',
    emptyState: 'Hasta que conectes campanas reales, esta vista debe permanecer sobria y sin promocionales inventados.',
    accent: 'oro',
    cards: [
      {
        id: 'campanas-promos',
        title: 'Promociones',
        description: 'Espacio reservado para campanas, periodos y estados comerciales vigentes.',
        note: 'Tabla relacionada: PROMOCION.',
        tone: 'oro',
        tags: ['PROMOCION', 'Campana', 'Vigencia'],
      },
      {
        id: 'campanas-productos',
        title: 'Productos promocionados',
        description: 'Cruce entre promociones y productos del catalogo para descuentos o visibilidad especial.',
        note: 'Tabla relacionada: PRODUCTO_PROMOCION.',
        tone: 'vino',
        tags: ['PRODUCTO_PROMOCION', 'Relacion', 'Catalogo'],
      },
      {
        id: 'campanas-puntaje',
        title: 'Puntaje',
        description: 'Panel enfocado en beneficios acumulados o recompensas del cliente.',
        note: 'Tabla relacionada: PUNTAJE.',
        tone: 'hoja',
        tags: ['PUNTAJE', 'Cliente', 'Fidelizacion'],
      },
    ],
  },
  {
    id: 'ventas',
    icon: 'credit-card',
    label: 'Ventas y pagos',
    eyebrow: 'Operacion comercial',
    title: 'Ventas y pagos',
    description: 'Reune el ciclo principal del pedido, su detalle, el pago asociado y el metodo utilizado.',
    emptyState: 'No se deben mostrar totales mientras no existan endpoints reales de pedido y pago.',
    accent: 'vino',
    cards: [
      {
        id: 'ventas-pedidos',
        title: 'Pedidos',
        description: 'Vista central para el registro maestro de cada compra del cliente.',
        note: 'Tabla relacionada: PEDIDO.',
        tone: 'vino',
        tags: ['PEDIDO', 'Compra', 'Estado'],
      },
      {
        id: 'ventas-detalle',
        title: 'Detalle del pedido',
        description: 'Muestra la relacion entre cada pedido y los productos que lo componen.',
        note: 'Tabla relacionada: PEDIDO_PRODUCTO.',
        tone: 'oro',
        tags: ['PEDIDO_PRODUCTO', 'Detalle', 'Items'],
      },
      {
        id: 'ventas-pagos',
        title: 'Pagos',
        description: 'Bloque destinado al seguimiento de cobros, confirmaciones y estados financieros.',
        note: 'Tabla relacionada: PAGO.',
        tone: 'grafito',
        tags: ['PAGO', 'Cobranza', 'Estado'],
      },
      {
        id: 'ventas-metodos',
        title: 'Metodos de pago',
        description: 'Area reservada para las opciones disponibles y su asociacion con cada cobro.',
        note: 'Tabla relacionada: METODO_PAGO.',
        tone: 'hoja',
        tags: ['METODO_PAGO', 'Canal', 'Configuracion'],
      },
    ],
  },
  {
    id: 'entregas',
    icon: 'truck',
    label: 'Entregas',
    eyebrow: 'Despacho y seguimiento',
    title: 'Entregas',
    description: 'Mantiene el foco en la entrega final, su seguimiento y la coordinacion con el pedido y el personal responsable.',
    emptyState: 'La vista de entregas debe mantenerse simple hasta que existan registros reales de seguimiento o despacho.',
    accent: 'grafito',
    cards: [
      {
        id: 'entregas-base',
        title: 'Entrega',
        description: 'Panel preparado para direccion, fecha, estado y detalles de cumplimiento.',
        note: 'Tabla relacionada: ENTREGA.',
        tone: 'grafito',
        tags: ['ENTREGA', 'Estado', 'Despacho'],
      },
      {
        id: 'entregas-pedido',
        title: 'Relacion con pedido',
        description: 'Area destinada a enlazar cada entrega con el pedido correspondiente cuando la data este activa.',
        note: 'Relacion operativa con PEDIDO.',
        tone: 'vino',
        tags: ['Pedido', 'Entrega', 'Seguimiento'],
      },
      {
        id: 'entregas-empleado',
        title: 'Responsable asignado',
        description: 'Espacio pensado para mostrar el empleado encargado y el avance del reparto.',
        note: 'Relacion operativa con EMPLEADO.',
        tone: 'oro',
        tags: ['Empleado', 'Asignacion', 'Ruta'],
      },
    ],
  },
]
